### ISSUE TITLE
使用Calibre管理你的本子——第二季 - 影子屋

### ISSUE THREAD

**Issue by yingziwu** [yingziwu/yingziwu.github.io#8]
https://blog.bgme.me/posts/use-calibre-to-manage-your-doujinshi-2/ 

 接前文，本文讲如何批量录入本子。

**Comment by originalMemory** [comment]
请问Calibre中如标签映射器等配置属性保存在C盘什么地方？
我用的是移动版，换了电脑之后，在原来电脑上保存的映射规则和添加书籍的正则找不到了

**Comment by yingziwu** [comment]
@originalMemory 
你好，经过实验，默认情況下 Calibre 配置目录位置如下，
Linux： `$HOME/.config/calibre`
Windows： `%APPDATA%\calibre`

具体而言，**Tag mapper** 规则存储于配置目录中的 **tag-map-rules.json** 文件中，导入文件识别作者、题名的正则表达式则储存于 **global.py** 文件中。  
你只需要备份相应目录中的所有文件即可。

不过，正常安装完 Calibre 便携版之后，在新建的 **Calibre Portable** 目录下含有三个目录、一个exe文件，如下图所示。

![calibre_portable_1](https://user-images.githubusercontent.com/22741471/32272692-25191182-bf3a-11e7-88ba-6ac69a9abfb6.png)

其中 **Calibre** 目录下存放软件本体，**Calibre Library** 为Calibre便携版的书库目录，**Calibre Setting** 则为Calibre便携版的设置目录，**calibre-portable.exe** 则为Calibre便携版的启动文件。

如果通过 **calibre-portable.exe** 启动Calibre，Calibre将使用当前目录下 **Calibre Library** 目录作为书库，并将相关设置保存在 **Calibre Setting** 目录中。   
**calibre-portable.exe** 文件必须与**Calibre** 目录存放于同一目录下，如果当前目录下没有 **Calibre Library**、**Calibre Setting**目录，使用 **calibre-portable.exe** 启动Calibre后将会在当前目录下创建这两个目录。  
此时应该不存在你说的这个问题。

如果使用 **Calibre** 目录中的 **calibre.exe** 文件启动Calibre，Calibre将会使用 `%APPDATA%\calibre` 目录作为配置文件存储目录，如果这是一台新机器的话（不存在 `%APPDATA%\calibre` 目录），此时会出现界面让你选择书库路径（如下图）。

![calibre_portable_2](https://user-images.githubusercontent.com/22741471/32274090-45d037ec-bf40-11e7-8e44-e51108607e14.png)

如果当前目录下没有 **Calibre Setting** 目录，使用 **calibre-portable.exe** 启动Calibre也会出现配置向导，但是你不能选择书库路径（如下图）。

![calibre_portable_3](https://user-images.githubusercontent.com/22741471/32274094-4cc740ae-bf40-11e7-9018-3b76c1e75ac8.png)

如果你是直接使用 **Calibre** 目录中的 **calibre.exe** 文件启动Calibre，则会出现你描述的这个问题。  

对于你问的这个问题，最简单的解决办法便是直接使用 **calibre-portable.exe** 文件启动Calibre便携版。如果你那里不存在 **calibre-portable.exe** 文件，你可以重新、下载安装最新版本的Calibre便携版，然后用你现在的书库目录替换 **calibre-portable.exe** 同目录下的 **Calibre Library** 目录即可。  
当然你也可以，每次备份、恢复 `%APPDATA%\calibre` 目录。

另外，你还可以通过修改 `CALIBRE_CONFIG_DIRECTORY` 环境变量来改变 Calibre 配置目录。  
因此，下面脚本的效果与 **calibre-portable.exe** 文件是一样的。

```
set CALIBRE_CONFIG_DIRECTORY=%cd%\Calibre Settings
set calibre_library=%cd%\Calibre Library
Calibre\calibre.exe --with-library="%calibre_library%"
```
如果你不想重新安装一遍，你可以在与 **Calibre** 同一层级的目录下创建一个上述内容的bat脚本，然后通过这个脚本来启动 Calibre。  

关于Calibre环境变量的更多信息，你可以参见[这里](https://manual.calibre-ebook.com/customize.html#environment-variables)。

**Comment by zerona2018** [comment]
问下，epub在calibre里打开是他自己的修改器，又慢又不需要。能改吗？win10机器的默认是浏览器，但是没有效果。

**Comment by zerona2018** [comment]
还有个问题，请问你用过calibre-web吗？他是否支持cbr或者cbz的文件格式？我看作者的最新版本支持，但是群晖的版本并不支持啊。

**Comment by yingziwu** [comment]
@zerona2018 
可以修改epub在calibre里的打开方式。
calibre会根据系统设置（即文件管理器中的相应格式的打开方式）来打开相应文件。所以，你可以再安装一个epub文档阅读器，然后在文件管理器中选择一个epub文件，通过右键菜单中打开方式，来修改相应格式的打开方式。
使用calibre自带的阅读器打开epub文件，我个人觉的速度还不错。不过打开cbz文件的确有点慢，这一点在文中也有提及，你可以参考[准备文件一节](https://blog.bgme.me/posts/use-calibre-to-manage-your-doujinshi-2/#id6)中的**使用插件部分**中修改修改cbz文件的默认打开方式的部分。

[calibre-web](https://github.com/janeczku/calibre-web)我没有用过，从Readme上看最新版好像是支持的，其它的我没用过也不好说，改天有空了的话会试一试的。

**Comment by yingziwu** [comment]
@zerona2018 
修改epub在calibre中的打开方式除了上面这种方法外，还有一种方式，这种方式仅仅修改calibre中的epub文件打开方式而不影响系统中的epub文件的打开方式。

1. 在calibre中选择一本epub格式的书籍。
1. 点击上方菜单栏中 **View** 按扭右边的三角箭头。
1. 在新的菜单中点击 **View specific format** 。
1. 在新窗口中，选择 **EPUB** ，点击 **Open EPUB with…**，然后选择相应的打开程序。
![i1](https://user-images.githubusercontent.com/22741471/34661810-1370ae72-f487-11e7-962b-1f3f3f75283c.png)

**Comment by zerona2018** [comment]
尝试在docker下的 ubuntu 里安装calibre 失败了

报错的信息：

Setting up command-line completion...
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/calibre
Setting up desktop integration...
xdg-icon-resource: No writable system icon directory found.

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


	Traceback (most recent call last):
	  File "site-packages/calibre/linux.py", line 813, in setup_desktop_integration
	  File "site-packages/calibre/linux.py", line 798, in install_icons
	  File "site-packages/calibre/linux.py", line 792, in install_single_icon
	  File "subprocess.py", line 541, in check_call
	CalledProcessError: Command '['xdg-icon-resource', 'install', '--noupdate', '--context', 'mimetypes', '--size', '16', 'application-lrf-16.png', 'application-lrf']' returned non-zero exit status 3

能帮看下是什么问题吗？

**Comment by zerona2018** [comment]
对了如果不管继续执行的话，又有个报错。
calibre
QXcbConnection: Could not connect to display :192.168.1.237:0.0
Aborted

**Comment by zerona2018** [comment]
好像是xdg-icon-resource 的问题。郁闷。类似 https://bugs.launchpad.net/calibre/+bug/1489654  这个。但是我这里问题没能解决。

**Comment by zerona2018** [comment]
搞定了，需要个vnc 服务。

**Comment by Ka0071m** [comment]
您好！我安装 Calibre3.18.0后，在安装 E-hentai Galleries插件时出现如下错误，请问是什么原因？
calibre, version 3.18.0
错误： 未处理的异常: <b>InvalidPlugin</b>:The plugin in u'F:\\tools\\

\u4f60\u7684\u672c\u5b50\u7ba1\u7406\\E-hentai Tag\\doujinshi_metadata_plugins-

1.1.2.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.18 Portable embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: E-hentai Galleries (1, 1, 2) && 

Embed Comic Metadata (1, 3, 8)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in 

add_plugin
  File "site-packages\calibre\customize\ui.py", line 461, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'F:\\tools\\\u4f60\u7684\u672c\u5b50\u7ba1\u7406\

\E-hentai Tag\\doujinshi_metadata_plugins-1.1.2.zip' is invalid. It does not 

contain a top-level __init__.py file

**Comment by yingziwu** [comment]
@Ka0071m
你好，请问这个问题解决了吗？

从错误信息上来看是由于你安装的插件zip文件有破损。
你可以尝试重新下载安装，下载后你可以先用解压缩工具（如winrar、7zip）看能否正常打开，没有问题后再进行安装。

**Comment by Ka0071m** [comment]
@yingziwu
最近出差，回来重新下载插件包，能用winrar解压，但还是安装出错，是因为我的系统有问题吗？ 我的是win7 64位系统。

**Comment by zerona2018** [comment]
https://download.calibre-ebook.com/3.html
看看老版本如何呢? 没必要一定用新的嘛.我这里还是3.17呢

**Comment by yiwcs** [comment]
请问下，使用这软件是不是就是原档和书库各有一份文件，这样感觉很占空间；或者添加完后把原档删除可以吗，转换成cbz可以减少大小吗

**Comment by zerona2018** [comment]
> @yiwcs
> 请问下，使用这软件是不是就是原档和书库各有一份文件，这样感觉很占空间；或者添加完后把原档删除可以吗，转换成cbz可以减少大小吗

对，是从新做了一个数据库出来。所以源文件想删也可以删掉了。

**Comment by MiriaPan** [comment]
我启动时遇到了：
QXcbConnection: Could not connect to display 
Aborted
calibre无法直接启动，我的系统是debian，错误的意思好像是因为没有显示器，我想知道怎么在终端运行QWQ

**Comment by guominpei** [comment]
请问calibre 默认打开书籍的时候怎么修改自己想用的阅读软件打开阅读了？

**Comment by yingziwu** [comment]
@HappyGORM 
> 请问calibre 默认打开书籍的时候怎么修改自己想用的阅读软件打开阅读了？

这个问题上面有提过，两种方法：
第一种方法便是修改系统中相应格式的打开方式，Calibre默认情况下会使用系统的打开方式。

> 可以修改epub在calibre里的打开方式。
> calibre会根据系统设置（即文件管理器中的相应格式的打开方式）来打开相应文件。所以，你可以再安装一个epub文档阅读器，然后在文件管理器中选择一个epub文件，通过右键菜单中打开方式，来修改相应格式的打开方式。
> 使用calibre自带的阅读器打开epub文件，我个人觉的速度还不错。不过打开cbz文件的确有点慢，这一点在文中也有提及，你可以参考[准备文件一节](https://blog.bgme.me/posts/use-calibre-to-manage-your-doujinshi-2/#id6)中的**使用插件部分**中修改修改cbz文件的默认打开方式的部分。
> ![sc2.png](https://camo.githubusercontent.com/865d3f925851f630996aadd5616645527154c84c/68747470733a2f2f626c6f672e62676d652e6d652f696d616765732f63616c696272652d646f756a696e7368692d322f7363322e706e67)

还有就是在Calibre中专门设置某格式的打开方式。

> 修改epub在calibre中的打开方式除了上面这种方法外，还有一种方式，这种方式仅仅修改calibre中的epub文件打开方式而不影响系统中的epub文件的打开方式。
> 
>1. 在calibre中选择一本epub格式的书籍。
> 2. 点击上方菜单栏中 **View** 按扭右边的三角箭头。
>3. 在新的菜单中点击 **View specific format** 。
>4. 在新窗口中，选择 **EPUB** ，点击 **Open EPUB with…**，然后选择相应的打开程序。
>![i1](https://user-images.githubusercontent.com/22741471/34661810-1370ae72-f487-11e7-962b-1f3f3f75283c.png)

**Comment by fnscar** [comment]
大佬你好。你的tag为什么是中文的，是用tag mapper转换的吗？但是我自己是试了下，手动一条一条地添加规则好麻烦的。。。
我看到github有个项目 EhTagTranslation/Database ，有没有办法把这个比较完整的翻译做成tag mapper的规则集？

**Comment by zerona2018** [comment]
> 大佬你好。你的tag为什么是中文的，是用tag mapper转换的吗？能不能贴个示例。

你看看是不是这个插件的因素链接：ehentai_metadata1.13  我想不起来是github 的哪个项目了。

**Comment by fnscar** [comment]
> @zerona2018
> > 大佬你好。你的tag为什么是中文的，是用tag mapper转换的吗？能不能贴个示例。
> 
> 你看看是不是这个插件的因素链接：ehentai_metadata1.13  我想不起来是github 的哪个项目了。

这个插件从eh抓到的tag就是英文的。。。应该是需要用tag mapper映射一下。

**Comment by xiazeyu** [comment]
安利一波LANraragi，贴连接自动下载，自动打标签，还能随机roll本子。服务器端自动解压，可以自定义压缩后的单张图片大小，且支持阅读进度的记录。美中不足的是暂时没有中文。
